import json

# 数据集
qa_data = [
    {"question": "What is the capital of Germany?", "answer": "Berlin"},
    {"question": "What is the largest planet?", "answer": "Jupiter"},
    {"question": "What is the currency of Japan?", "answer": "Yen"},
    {"question": "What is the main language spoken in Spain?", "answer": "Spanish"},
    {"question": "What is the capital of France?", "answer": "Paris"},
    {"question": "What is the largest mammal?", "answer": "Whale"},
    {"question": "What is the chemical symbol for water?", "answer": "H2O"},
    {"question": "What is the capital of Italy?", "answer": "Rome"},
    {"question": "What is the largest ocean?", "answer": "Pacific"},
    {"question": "What is the chemical symbol for oxygen?", "answer": "O2"},
    {"question": "What is the capital of the USA?", "answer": "Washington"},
    {"question": "What is the main language spoken in Canada?", "answer": "English"},
    {"question": "What is the smallest continent?", "answer": "Australia"},
    {"question": "What is the main ingredient in bread?", "answer": "Flour"},
    {"question": "What is the capital of Australia?", "answer": "Canberra"},
    {"question": "What is the largest bird?", "answer": "Ostrich"},
    {"question": "What is the chemical symbol for carbon?", "answer": "C"},
    {"question": "What is the capital of China?", "answer": "Beijing"},
    {"question": "What is the main language spoken in Japan?", "answer": "Japanese"},
    {"question": "What is the largest continent?", "answer": "Asia"},
    {"question": "What is the currency of India?", "answer": "Rupee"},
    {"question": "What is the capital of Spain?", "answer": "Madrid"},
    {"question": "What is the currency of the UK?", "answer": "Pound"},
    {"question": "What is the main ingredient in pizza dough?", "answer": "Flour"},
    {"question": "What is the chemical symbol for hydrogen?", "answer": "H2"},
    {"question": "What is the capital of Russia?", "answer": "Moscow"},
    {"question": "What is the smallest ocean?", "answer": "Arctic"},
    {"question": "What is the main language spoken in Italy?", "answer": "Italian"},
    {"question": "What is the chemical symbol for gold?", "answer": "Au"},
    {"question": "What is the capital of Canada?", "answer": "Ottawa"},
    {"question": "What is the largest desert?", "answer": "Sahara"},
    {"question": "What is the main language spoken in Germany?", "answer": "German"},
    {"question": "What is the currency of France?", "answer": "Euro"},
    {"question": "What is the largest land animal?", "answer": "Elephant"},
    {"question": "What is the smallest bird?", "answer": "Hummingbird"},
    {"question": "What is the currency of Russia?", "answer": "Ruble"},
    {"question": "What is the largest reptile?", "answer": "Saltwater crocodile"},
    {"question": "What is the main language spoken in Brazil?", "answer": "Portuguese"},
    {"question": "What is the capital of Argentina?", "answer": "Buenos Aires"},
    {"question": "What is the smallest country?", "answer": "Vatican"},
    {"question": "What is the chemical symbol for iron?", "answer": "Fe"},
    {"question": "What is the capital of South Africa?", "answer": "Pretoria"},
    {"question": "What is the largest lake?", "answer": "Caspian"},
    {"question": "What is the hottest desert?", "answer": "Sahara"},
    {"question": "What is the main language spoken in Russia?", "answer": "Russian"},
    {"question": "What is the largest canyon?", "answer": "Grand Canyon"},
    {"question": "What is the smallest planet?", "answer": "Mercury"},
    {"question": "What is the largest sea?", "answer": "Philippine"},
    {"question": "What is the capital of Egypt?", "answer": "Cairo"},
    {"question": "What is the largest mountain?", "answer": "Everest"},
    {"question": "What is the main ingredient in sushi?", "answer": "Rice"},
    {"question": "What is the capital of Turkey?", "answer": "Ankara"},
    {"question": "What is the smallest fish?", "answer": "Paedocypris"},
    {"question": "What is the currency of Australia?", "answer": "Dollar"},
    {"question": "What is the largest bay?", "answer": "Bengal"},
    {"question": "What is the main ingredient in tea?", "answer": "Tea leaves"},
    {"question": "What is the largest river?", "answer": "Amazon"},
    {"question": "What is the capital of Thailand?", "answer": "Bangkok"},
    {"question": "What is the largest swamp?", "answer": "Pantanal"},
    {"question": "What is the smallest country in Africa?", "answer": "Seychelles"},
    {"question": "What is the largest glacier?", "answer": "Lambert"},
    {"question": "What is the main language spoken in Thailand?", "answer": "Thai"},
    {"question": "What is the largest peninsula?", "answer": "Arabian"},
    {"question": "What is the smallest star?", "answer": "Proxima"},
    {"question": "What is the largest atoll?", "answer": "Kiritimati"},
    {"question": "What is the largest rainforest?", "answer": "Amazon"},
    {"question": "What is the smallest tree?", "answer": "Dwarf Willow"},
    {"question": "What is the main ingredient in coffee?", "answer": "Coffee beans"},
    {"question": "What is the largest waterfall?", "answer": "Victoria"},
    {"question": "What is the largest island?", "answer": "Greenland"},
    {"question": "What is the hottest place on Earth?", "answer": "Death Valley"},
    {"question": "What is the largest mountain range?", "answer": "Himalayas"},
    {"question": "What is the largest plateau?", "answer": "Tibetan"},
    {"question": "What is the main language spoken in Kenya?", "answer": "Swahili"},
    {"question": "What is the largest gulf?", "answer": "Mexico"},
    {"question": "What is the capital of Peru?", "answer": "Lima"},
    {"question": "What is the largest waterfall in Africa?", "answer": "Victoria"}
]

# The `qa_list` now follows the format you requested and contains 100 Q-A pairs. Let me know if you need this saved or further modifications!


# 保存为 JSON 文件
with open("qa_dataset.json", "w", encoding="utf-8") as f:
    json.dump(qa_data, f, indent=4)

print("Dataset saved to qa_dataset.json")
